---
# tasks file for vscode
- name: add vscode gpg apt key
  apt_key:
   url: https://packages.microsoft.com/keys/microsoft.asc
   state: present

- name: add vscode repository
  apt_repository:
   repo: deb https://packages.microsoft.com/repos/vscode stable main
   state: present

- name: install vscode
  apt: update_cache=yes name=code state=present
  
