---
# tasks file for spotify
#
- name: add spotify gpg apt key
  apt_key:
   url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
   state: present

- name: add spotify repository
  apt_repository:
   repo: deb http://repository.spotify.com stable non-free
   state: present

- name: install spotify
  apt: update_cache=yes name=spotify-client state=present

