---
# tasks file for nvim

- name: install dependencies
  apt:
    name:
      - git
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present

- name: ensure that neovim folder doesn´t exist
  file:
    path: /tmp/neovim
    state: absent

- name: Create a new neovim foler
  file:
    path: /tmp/neovim
    state: directory

- name: install neovim
  command: "{{ item }}"
  with_items:
    - git clone https://github.com/neovim/neovim.git /tmp/neovim
    - bash -c "cd /tmp/neovim && make"
    - bash -c "cd /tmp/neovim && make install"

- name: clone vim configs
  command:
    argv:
      - git
      - clone
      - https://gitlab.com/wenceslao1207/vim-configs
      - /home/{{ user }}/src/vim-configs

- name: Create nvim config folder
  file:
    path: /home/{{ user }}/.config/nvim
    state: directory

- name: setup vim configs
  copy:
    src: /home/{{ user }}/src/vim-configs/
    dest: /home/{{ user }}

- name: setup vimrcs
  copy:
    src: /home/{{ user }}/src/vim-configs/vimrc
    dest: /home/{{ user }}/.vimrc

- name: setup nvim
  copy:
    src: /home/{{ user }}/src/vim-configs/init.vim
    dest: /home/{{ user }}/.config/nvim

- name: set ownership of user's home
  file:
    path: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Remove vim configs source
  file:
    path: /home/{{ user }}/src/vim-configs
    state: absent

- name: Create vim autoload folder
  file:
    path: /home/{{ user }}/.vim/autoload
    state: directory

- name: install vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ user }}/.vim/autoload/plug.vim
