---
# tasks file for nvim

- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - ninja-build
    - gettext
    - libtool
    - libtool-bin 
    - autoconf 
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
    - curl
    - doxygen

- name: prepare fs neovim
  command: rm -rf /tmp/neovim && mkdir /tmp/neovim

- name: install neovim
  command: "{{ item }}"
  with_items:
    - git clone https://github.com/neovim/neovim.git /tmp/neovim
    - bash -c "cd /tmp/neovim && make"
    - bash -c "cd /tmp/neovim && make install"

- name: clone vim configs
  command:
    argv:
      - git
      - clone
      - https://gitlab.com/wenceslao1207/vim-configs
      - /home/{{ user }}/src/vim-configs

- name: setup vim configs
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/{{ user }}/.config/nvim
    - cp /home/{{ user }}/src/vim-configs/.nvimrc /home/{{ user }}
    - cp /home/{{ user }}/src/vim-configs/vimrc /home/{{ user }}/.vimrc
    - cp /home/{{ user }}/src/vim-configs/init.vim /home/{{ user }}/.config/nvim
    - chown -R {{ user }}:{{ user }} /home/{{ user }}/
    - rm -rf /home/{{ user }}/src/vim-configs

- name: install vim plug
  command:
    argv:
      - curl
      - -fLo
      - /home/{{ user }}/.vim/autoload/plug.vim
      - --create-dirs
      - https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
